// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace prueba_clt_sa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119101851_SeedInitialDB")]
    partial class SeedInitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Asunción",
                            Country = "Paraguay",
                            Street = "Calle Falsa 123",
                            UserId = 1,
                            ZipCode = "9999"
                        },
                        new
                        {
                            Id = 2,
                            City = "Asunción",
                            Country = "Paraguay",
                            Street = "Palma 456",
                            UserId = 1,
                            ZipCode = "1001"
                        },
                        new
                        {
                            Id = 3,
                            City = "Santa Rosa",
                            Country = "Paraguay",
                            Street = "Mcal. Estigarribia 789",
                            UserId = 2,
                            ZipCode = "6400"
                        },
                        new
                        {
                            Id = 4,
                            City = "Asunción",
                            Country = "Paraguay",
                            Street = "Aviadores del Chaco 321",
                            UserId = 3,
                            ZipCode = "1205"
                        },
                        new
                        {
                            Id = 5,
                            City = "Luque",
                            Country = "Paraguay",
                            Street = "Cerro Corá 555",
                            UserId = 4,
                            ZipCode = "2060"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateToBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PYG",
                            Name = "Guaraní Paraguayo",
                            RateToBase = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            Name = "Dólar Estadounidense",
                            RateToBase = 7300.0m
                        },
                        new
                        {
                            Id = 3,
                            Code = "BRL",
                            Name = "Real Brasileño",
                            RateToBase = 1350.0m
                        },
                        new
                        {
                            Id = 4,
                            Code = "ARS",
                            Name = "Peso Argentino",
                            RateToBase = 8.5m
                        },
                        new
                        {
                            Id = 5,
                            Code = "EUR",
                            Name = "Euro",
                            RateToBase = 8100.0m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tobias@example.com",
                            IsActive = true,
                            Name = "Tobias Almada",
                            Password = "hashed_password_1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "patricio@example.com",
                            IsActive = true,
                            Name = "Patricio Lopez",
                            Password = "hashed_password_2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "juan@test.com",
                            IsActive = true,
                            Name = "Juan Perez",
                            Password = "hashed_password_3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "maria@test.com",
                            IsActive = true,
                            Name = "Maria Garcia",
                            Password = "hashed_password_4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "carlos@test.com",
                            IsActive = true,
                            Name = "Carlos Lopez",
                            Password = "hashed_password_5"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
